% consultar este archivo y escribir "test."


:-consult('main.pl').
test:-
    option(1, "1) Viajar", 1, 1, ["viajar", "turistear", "conocer"], OP1),
    option(2, "2) Estudiar", 2, 1, ["estudiar", "aprender", "perfeccionarme"], OP2),
    flow(1, "flujo1", [OP1], F10),
    flowAddOption(F10, OP2, F11),
    chatbot(0, "Inicial", "Bienvenido\n¿Qué te gustaría hacer?", 1, [F11], CB0),
    option(1, "1) New York, USA", 1, 2, ["USA", "Estados Unidos", "New York"], OP3),
    option(2, "2) París, Francia", 1, 1, ["Paris", "Eiffel"], OP4),
    option(3, "3) Torres del Paine, Chile", 1, 1, ["Chile", "Torres", "Paine", "Torres Paine", "Torres del Paine"], OP5),
    option(4, "4) Volver", 0, 1, ["Regresar", "Salir", "Volver"], OP6),
    option(1, "1) Central Park", 1, 2, ["Central", "Park", "Central Park"], OP7),
    option(2, "2) Museos", 1, 2, ["Museo"], OP8),
    option(3, "3) Ningún otro atractivo", 1, 3, ["Museo"], OP9),
    option(4, "4) Cambiar destino", 1, 1, ["Cambiar", "Volver", "Salir"], OP10),
    option(1, "1) Solo", 1, 3, ["Solo"], OP11),
    option(2, "2) En pareja", 1, 3, ["Pareja"], OP12),
    option(3, "3) En familia", 1, 3, ["Familia"], OP13),
    option(4, "4) Agregar más atractivos", 1, 2, ["Volver", "Atractivos"], OP14),
    option(5, "5) En realidad quiero otro destino", 1, 1, ["Cambiar destino"], OP15),
    flow(1, "Flujo 1 Chatbot1\n¿Dónde te Gustaría ir?", [OP3, OP4, OP5, OP6], F20),
    flow(2, "Flujo 2 Chatbot1\n¿Qué atractivos te gustaría visitar?", [OP7, OP8, OP9, OP10], F21),
    flow(3, "Flujo 3 Chatbot1\n¿Vas solo o acompañado?", [OP11, OP12, OP13, OP14, OP15], F22),
    chatbot(1, "Agencia Viajes",  "Bienvenido\n¿Dónde quieres viajar?", 1, [F20, F21, F22], CB1),
    option(1, "1) Carrera Técnica", 2, 1, ["Técnica"], OP16),
    option(2, "2) Postgrado", 2, 1, ["Doctorado", "Magister", "Postgrado"], OP17),
    option(3, "3) Volver", 0, 1, ["Volver", "Salir", "Regresar"], OP18),
    flow(1, "Flujo 1 Chatbot2\n¿Qué te gustaría estudiar?", [OP16, OP17, OP18], F30),
    chatbot(2, "Orientador Académico",  "Bienvenido\n¿Qué te gustaría estudiar?", 1, [F30], CB2),
    system("Chatbots Paradigmas", 0, [CB0], S0),
    systemAddChatbot(S0, CB1, S01),
    systemAddChatbot(S01, CB2, S02),
    systemAddUser(S02, "user1", S2),
    systemAddUser(S2, "user2", S3),
    systemAddUser(S3, "user3", S5),
    systemLogin(S5, "user1", S7),
    systemLogout(S7, S9),
    systemLogin(S9, "user2", S10),
    /* systemTalkRec systemSynthesis y systemSimulate presentan problemas de implementacion es por eso que estan comentados
    systemTalkRec(S10, "hola", S11),
    systemTalkRec(S11, "1", S12),
    systemTalkRec(S12, "1", S13),
    systemTalkRec(S13, "Museo", S14),
    systemTalkRec(S14, "1", S15),
    systemTalkRec(S15, "3", S16),
    systemTalkRec(S16, "5", S17),
    systemSynthesis(S17, "user2", Str1),
    systemSimulate(S02, 5, 32131, S99),
    */
    write("OP1= "),write(OP1), write("\n"),
    write("OP2= "),write(OP2), write("\n"),
    write("F10= "),write(F10), write("\n"),
    write("F11= "),write(F11), write("\n"),
    write("CB0= "),write(CB0), write("\n"),
    write("OP3= "),write(OP3), write("\n"),
    write("OP4= "),write(OP4), write("\n"),
    write("OP5= "),write(OP5), write("\n"),
    write("OP6= "),write(OP6), write("\n"),
    write("OP7= "),write(OP7), write("\n"),
    write("OP8= "),write(OP8), write("\n"),
    write("OP9= "),write(OP9), write("\n"),
    write("OP10= "),write(OP10), write("\n"),
    write("OP11= "),write(OP11), write("\n"),
    write("OP12= "),write(OP12), write("\n"),
    write("OP13= "),write(OP13), write("\n"),
    write("OP14= "),write(OP14), write("\n"),
    write("OP15= "),write(OP15), write("\n"),
    write("F20= "),write(F20), write("\n"),
    write("F21= "),write(F21), write("\n"),
    write("F22= "),write(F22), write("\n"),
    write("CB1= "),write(CB1), write("\n"),
    write("OP16= "),write(OP16), write("\n"),
    write("OP17= "),write(OP17), write("\n"),
    write("OP18= "),write(OP18), write("\n"),
    write("F30= "),write(F30), write("\n"),
    write("CB2= "),write(CB2), write("\n"),
    write("S0= "),write(S0), write("\n"),
    write("S01= "),write(S01), write("\n"),
    write("S02= "),write(S02), write("\n"),
    write("S2= "),write(S2), write("\n"),
    write("S3= "),write(S3), write("\n"),
    write("S5= "),write(S5), write("\n"),
    write("S7= "),write(S7), write("\n"),
    write("S9= "),write(S9), write("\n"),
    write("S10= "),write(S10), write("\n").

/* descomentar si se desea probar otro script, tambien puede copiar el script y probarlo consultando en el main
test2:-
    option(1, "1) Buscar peliculas", 1, 1, ["peliculas", "pelis", "movies"], OP1),
    option(2, "2) Buscar videojuegos", 2, 1, ["juegos", "videojuegos", "jugar"], OP2),
    flow(1, "flujo1", [OP1], F10),
    flowAddOption(F10, OP2, F11),
    chatbot(0, "Inicial", "Bienvenido\n¿Qué te gustaría hacer?", 1, [F11], CB0),
    option(1, "1) Terror", 1, 2, ["Miedo", "Horror", "Suspenso"], OP3),
    option(2, "2) Fantasia y ciencia ficcion", 1, 1, ["Fantasia", "Ciencia ficcion"], OP4),
    option(3, "3) Comedia", 1, 1, ["Diversion", "Comedy", "Risa", "Chistosa", "Entretenida"], OP5),
    option(4, "4) Volver", 0, 1, ["Regresar", "Salir", "Volver"], OP6),
    option(1, "1) 2023", 1, 2, ["Este año", "actuales", "estreno"], OP7),
    option(2, "2) anteriores", 1, 2, ["Antiguas"], OP8),
    option(3, "3) Proximamente", 1, 3, ["Por estrenar"], OP9),
    option(4, "4) Cambiar categoria", 1, 1, ["Cambiar", "Volver", "Salir"], OP10),
    option(1, "1) Autor", 1, 3, ["Autor"], OP11),
    option(2, "2) Reparto", 1, 3, ["Reparto"], OP12),
    option(3, "3) Duracion", 1, 3, ["Duracion"], OP13),
    option(4, "4) Otro año", 1, 2, ["Volver", "Años"], OP14),
    option(5, "5) Cambiar categoria", 1, 1, ["Cambiar"], OP15),
    flow(1, "Flujo 1 Chatbot1\n¿Que categoria te gustaria ver?", [OP3, OP4, OP5, OP6], F20),
    flow(2, "Flujo 2 Chatbot1\n¿De que año te gustaria ver?", [OP7, OP8, OP9, OP10], F21),
    flow(3, "Flujo 3 Chatbot1\n¿Que otro filtro deseas agregar?", [OP11, OP12, OP13, OP14, OP15], F22),
    chatbot(1, "Buscador de peliculas",  "Bienvenido\n¿Que pelicula te gustaria ver?", 1, [F20, F21, F22], CB1),
    option(1, "1) Singleplayer", 2, 1, ["solo"], OP16),
    option(2, "2) Multiplayer", 2, 1, ["Multijugador", "MMO", "Online"], OP17),
    option(3, "3) Volver", 0, 1, ["Volver", "Salir", "Regresar"], OP18),
    flow(1, "Flujo 1 Chatbot2\n¿Qué te gustaría jugar?", [OP16, OP17, OP18], F30),
    chatbot(2, "Buscador de juegos",  "Bienvenido\n¿Qué te gustaría jugar?", 1, [F30], CB2),
    system("Chatbots Paradigmas", 0, [CB0], S0),
    systemAddChatbot(S0, CB1, S01),
    systemAddChatbot(S01, CB2, S02),
    systemAddUser(S02, "user1", S2),
    systemAddUser(S2, "user2", S3),
    systemAddUser(S3, "user3", S5),
    systemLogin(S5, "user1", S7),
    systemLogout(S7, S9),
    systemLogin(S9, "user2", S10),
    write("OP1= "),write(OP1), write("\n"),
    write("OP2= "),write(OP2), write("\n"),
    write("F10= "),write(F10), write("\n"),
    write("F11= "),write(F11), write("\n"),
    write("CB0= "),write(CB0), write("\n"),
    write("OP3= "),write(OP3), write("\n"),
    write("OP4= "),write(OP4), write("\n"),
    write("OP5= "),write(OP5), write("\n"),
    write("OP6= "),write(OP6), write("\n"),
    write("OP7= "),write(OP7), write("\n"),
    write("OP8= "),write(OP8), write("\n"),
    write("OP9= "),write(OP9), write("\n"),
    write("OP10= "),write(OP10), write("\n"),
    write("OP11= "),write(OP11), write("\n"),
    write("OP12= "),write(OP12), write("\n"),
    write("OP13= "),write(OP13), write("\n"),
    write("OP14= "),write(OP14), write("\n"),
    write("OP15= "),write(OP15), write("\n"),
    write("F20= "),write(F20), write("\n"),
    write("F21= "),write(F21), write("\n"),
    write("F22= "),write(F22), write("\n"),
    write("CB1= "),write(CB1), write("\n"),
    write("OP16= "),write(OP16), write("\n"),
    write("OP17= "),write(OP17), write("\n"),
    write("OP18= "),write(OP18), write("\n"),
    write("F30= "),write(F30), write("\n"),
    write("CB2= "),write(CB2), write("\n"),
    write("S0= "),write(S0), write("\n"),
    write("S01= "),write(S01), write("\n"),
    write("S02= "),write(S02), write("\n"),
    write("S2= "),write(S2), write("\n"),
    write("S3= "),write(S3), write("\n"),
    write("S5= "),write(S5), write("\n"),
    write("S7= "),write(S7), write("\n"),
    write("S9= "),write(S9), write("\n"),
    write("S10= "),write(S10), write("\n").
*/